version: "3"
services:
 myportfolio:
   container_name: myportfolio
   build: .
   restart: always
   env_file:
    - .env
   environment:
    - FLASK_ENV=development
    - SUBDOMAINS=sankalp-portfolio.duckdns.org
    - TOKEN=045bfa6d-499c-4d6a-b046-763f69a22391
   ports:
    - "5000:5000"
   volumes:
    - .:/myportfolio
   depends_on:
    - mysql
 mysql:
   container_name: mysql
   image: mariadb
   restart: always
   env_file:
    - .env
   volumes:
    - mydatabase:/var/lib/mysql
   restart: unless-stoppped

volumes:
  mydatabase:
